services:
  kong:
    build: ./kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PLUGINS: bundled
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    deploy:
      resources:
        limits:
          memory: 256M
